### ISSUE TITLE
Suggestion: Only Active if on Arceuus Spellbook

### ISSUE THREAD

**Issue by DivineInsanity** [PortAGuy/thrall-helper#1]
Love the plugin, helpful for dummies like myself to remember. Would be awesome if it was only active in making the infobox happen based on the spellbook you're on. I'm pretty much *only* on Arceuus book when doing activities with thralls, so would be nice to be able to leave the plugin perma on, instead of toggling the plugin off whenever not doing an activity with thralls.

**Comment by PortAGuy** [comment]
I've updated the plugin with a better system so after summoning a thrall if you don't summon another for a configurable amount of time, it will remove the prompt. Thanks for the suggestion!

**Comment by asherbasher** [comment]
Liking the plugin but I do think it would still be better if it only activated when you're on the Arceuus spellbook and have the book/runes with you.

**Comment by PortAGuy** [comment]
I ended up deciding to include this feature and it will be available once the plugin is updated.
