### ISSUE TITLE
Make the reminder message configurable.

### ISSUE THREAD

**Issue by Reeenatu** [PortAGuy/thrall-helper#11]
It would be nice to customize our own reminder message, for example, i dont like to see the "You need to summon a thrall!" message, i'd rather put something like... "Thrall", thats enough to me, same for the "You need to death charge" => "Death Charge/ Charge".
P.S: I use fixed client and yeah.. the messages above can occupy a large space on the screen.

**Comment by Reeenatu** [comment]
![image](https://user-images.githubusercontent.com/16688838/236696252-6b85455b-f9f9-4142-a1d1-a24b7b7f7324.png)

**Comment by Reeenatu** [comment]
Any thoughts on this one??? Doesnt seem to be a hard change

**Comment by Kurisu92** [comment]
Any updates on this?

**Comment by PortAGuy** [comment]
Added in the latest update
