### ISSUE TITLE
Suggestion: Add Prayer and Run Energy Reminder?

### ISSUE THREAD

**Issue by Simpuhl** [PortAGuy/thrall-helper#15]
I like the way you have your Thrall window flashing, and I thought you could make two more add-ins or maybe create an AIO...

- Thrall Reminder
- Prayer is below X amount
- Run energy is below X amount
- Vengeance reminder

I am sure there are many more... but prayer and run energy would be super important. I am fighting Muspah boss and I keep forgetting to pop an energy or prayer potion but never a thrall.

 
I know there are some other plugins out there but the way yours flashes is great.

**Comment by PortAGuy** [comment]
I think this plugin should focus on providing a thrall reminder. I believe the Watchdog plugin has some of the features you are looking for, or you could configure runelite to show notifications when low on run/prayer with the base plugins.
