### ISSUE TITLE
ToA indefinite reminder box (won't disappear)

### ISSUE THREAD

**Issue by Runebyte** [PortAGuy/thrall-helper#6]
Changing instances in Tombs of Amascut (and presumably other instances) prevents the reminder box from disappearing regardless of timeout config.

**Comment by PortAGuy** [comment]
That's strange, are you able to reproduce this consistently? This plugin doesn't check instance or the location of the player, only looks for the chat messages.

**Comment by PortAGuy** [comment]
Closing as it has been two years with nobody able to reproduce.
