### ISSUE TITLE
Ability to disable "Ressurect thrall cooldown" info box.

### ISSUE THREAD

**Issue by SandroVA** [PortAGuy/thrall-helper#9]
I personally don't need to know when thralls are on cooldown

**Comment by PortAGuy** [comment]
Hi there!

This isn't actually a feature within the thrall helper plugin. I believe what you are referring to is an option within the base RuneLite client plugin named "Timers".

Can you check if you have the "Arceuus spells cooldown" option on in that plugin? I believe this describes the behaviour you are talking about.

If it's not the base RuneLite plugin, then it is most likely to be some other external plugin.

Hope this helps!
